add error check in deactivate

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -3,7 +3,7 @@
 
 # Ensure that this script is sourced, not executed.
 if [[ "$(basename "$0" 2> /dev/null)" == "activate" ]]; then
-    echo >&2 "Error: activate must be sourced. Run 'source activate envname' instead of 'activate envname'."
+    echo >&2 "SyntaxError: activate must be sourced. Run 'source activate envname' instead of 'activate envname'."
     return 1
 fi
 
@@ -28,7 +28,7 @@ fi
 
 # Activate Virtual Environment
 if [ $? -ne 0 ]; then
-    echo >&2 "RuntimeError: environment is not been activated."
+    echo >&2 "RuntimeError: activating failed."
     return 1
 else
     source "~/Envs/${1}/bin/activate"
diff --git a/deactivate b/deactivate
--- a/deactivate
+++ b/deactivate
@@ -1,8 +1,22 @@
 #!/bin/bash
 
 
-# deactivate virtual environment
-if [ -n "${VIRTUAL_ENV}" ]; then
+# Ensure that this script is sourced, not executed.
+if [[ "$(basename "$0" 2> /dev/null)" == "deactivate" ]]; then
+    echo >&2 "SyntaxError: deactivate must be sourced. Run 'source deactivate' instead of 'deactivate'."
+    return 1
+fi
+
+# Check that if there is no activated virtual environment.
+if [ -z "${VIRTUAL_ENV}" ]; then
+    return 0
+fi
+
+# Deactivate the current virtual environment.
+if [ $? -ne 0 ]; then
+    echo >&2 "RuntimeError: deactivating failed."
+    return 1
+else
     deactivate
 fi
 
